# Use an official Python runtime as base image
FROM python:3.8

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . /app

# Run your script when the container launches
CMD ["python", "test.py"]